# Simple Machine Learning - a model which learns how to add two numbers

In [3]:
import numpy as np 
try:
    import pandas as pd
except ModuleNotFoundError:
    ! pip3 install pandas
    import pandas as pd
    
np.set_printoptions(suppress='true',precision=1)    
   

In [4]:
# The original data generating thing. just every few numbers. 
# worked ok if you made it every single number
# generate the training data as a simple formula
train_data = np.array([[1.0,1.0]])
train_targets = np.array([2.0])
for i in range(20,10000,1):
    train_data= np.append(train_data,[[i,i*2]],axis=0)
    train_targets= np.append(train_targets,[i+i*2])

# not a particularly representative lot
test_data = np.array([[2.0,2.0]])
test_targets = np.array([4.0])
for i in range(4,8000,4):
    test_data = np.append(test_data,[[i,i*2]],axis=0)
    test_targets = np.append(test_targets,[i+i*2])

## Latin Hypercube data sets

In [6]:
# now use the latin hypercube to make a sample 
try:
    import lhsmdu
except ModuleNotFoundError:
    ! pip3 install lhsmdu
    import lhsmdu
    
import matplotlib.pyplot as plt
import numpy
from numpy import array

# print 5 digits of precision
np.set_printoptions(suppress='true',precision=5) 


You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


In [7]:
# First generate the test data with Latin Hypercube
l = lhsmdu.sample(10000,2,randomSeed=10) # Latin Hypercube Sampling of two variables, and 10 samples each.

# coming out it's a fraction between 0 and 1. Move the decimal over a bit... 
m= l * 10000

trainx_data = np.array([[1.0,1.0]])
trainx_targets = np.array([2.0])

for list in m:
    # it's [[i,j]] - a matrix. kinda hard to reach in there. Change it to an array
    # and you can subscript it and round to an integer
    a = array(list)
    i = round(a[0][0])
    j = round(a[0][1])
    # 1 = addition
    trainx_data= np.append(trainx_data,[[i,j]],axis=0)
    trainx_targets= np.append(trainx_targets,[i+j])



In [8]:
# Use Monte Carlo Sampling this time 

k = lhsmdu.createRandomStandardUniformMatrix(10000,2) # Monte Carlo Sampling
n = k * 10000

testx_data = np.array([[1.0,1.0]])
testx_targets = np.array([2.0])

for list in n:
    # it's [[i,j]] - a matrix. kinda hard to reach in there. Change it to an array
    # and you can subscript it and round to an integer
    a = array(list)
    i = round(a[0][0])
    j = round(a[0][1])
    # make a third 
 
    testx_data= np.append(testx_data,[[i,j]],axis=0)
    testx_targets= np.append(testx_targets,[i+j])

In [9]:
print("trainx_data\n",trainx_data)
print("test_data\n",test_data)

trainx_data
 [[   1.    1.]
 [6095.   85.]
 [3492. 8466.]
 ...
 [2178. 5480.]
 [4681. 5215.]
 [6073. 3834.]]
test_data
 [[    2.     2.]
 [    4.     8.]
 [    8.    16.]
 ...
 [ 7988. 15976.]
 [ 7992. 15984.]
 [ 7996. 15992.]]


In [10]:
trainx_targets[0:4]

array([    2.,  6180., 11958., 12393.])

In [11]:
trainx_data.shape


(10001, 2)

## Train the model

In [13]:
# Actually run the training, and then ask a couple questions, 
# kick back and wait for the answer
# This takes a while

import tensorflow as tf
from tensorflow import keras
import numpy as np
#import data_creation as dc 

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(2,)),
    keras.layers.Dense(200, activation=tf.nn.relu),
    keras.layers.Dense(600, activation=tf.nn.relu),
    keras.layers.Dense(200, activation=tf.nn.relu),
    keras.layers.Dense(1)
])

model.compile(optimizer='adam', 
              loss='mse',
              metrics=['mae'])

model.fit(trainx_data, trainx_targets, epochs=12
          , batch_size=50)



Epoch 1/12
201/201 [==============================] - 1s 3ms/step - loss: 1823552.0000 - mae: 455.9235
Epoch 2/12
201/201 [==============================] - 1s 3ms/step - loss: 172.9953 - mae: 9.7963
Epoch 3/12
201/201 [==============================] - 1s 3ms/step - loss: 52.1010 - mae: 5.3261
Epoch 4/12
201/201 [==============================] - 1s 3ms/step - loss: 18.8851 - mae: 3.1823
Epoch 5/12
201/201 [==============================] - 1s 3ms/step - loss: 8.9618 - mae: 2.1910
Epoch 6/12
201/201 [==============================] - 1s 3ms/step - loss: 5.4376 - mae: 1.7176
Epoch 7/12
201/201 [==============================] - 1s 3ms/step - loss: 3.7397 - mae: 1.4265
Epoch 8/12
201/201 [==============================] - 1s 3ms/step - loss: 2.6216 - mae: 1.1939
Epoch 9/12
201/201 [==============================] - 1s 3ms/step - loss: 1.9572 - mae: 1.0375
Epoch 10/12
201/201 [==============================] - 1s 3ms/step - loss: 1.5325 - mae: 0.9247
Epoch 11/12
201/201 [================

## Now check the model's algorithm against some known values

In [ ]:
test_loss, test_acc = model.evaluate(testx_data, testx_targets)
print('Test accuracy:', test_acc)
a= np.array([[2000,3000],
             [4,5],
             [3,5987],
            [12,17]])
print(model.predict(a))

In [ ]:
b= np.array([[38,22],[4,5],[10000.,20000.]])
np.set_printoptions(suppress='true',precision=2)   
print(model.predict(b))